### ISSUE TITLE
solver fails with duplicate key value violation

### ISSUE THREAD

**Issue by harshad16** [thoth-station/solver#1640]
**Describe the bug**

The solver was triggered from the management API.
Even though the package was already ingested. However, this seems to be due to the metadata: `'python_package_metadata_id': 151600`

```
SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id, is_missing, provides_source_distro) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s, %(is_missing)s, %(provides_source_distro)s) RETURNING python_package_version.id]
[parameters: {'package_name': 'selinon', 'package_version': '1.0.0', 'os_name': 'rhel', 'os_version': '8', 'python_version': '3.8', 'entity_id': 1, 'python_package_index_id': 1, 'python_package_metadata_id': 151600, 'is_missing': False, 'provides_source_distro': True}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-10-08 14:53:03,143   1 CRITICAL root:105: Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(selinon, 1.0.0, 1, rhel, 8, 3.8) already exists.
```

**Additional context**
http://pastebin.test.redhat.com/1000711

**Comment by harshad16** [comment]
closing this issue
as we dont expect graph-refresh job to submit the same package twice.
this is due to user submission, which is fine, if it results in failure.

**Comment by fridex** [comment]
> this is due to user submission, which is fine, if it results in failure.

I would keep this open. We should be able to trigger (re)analyzes a package that can have eventually other metadata and this behavior should not happen.
