### ISSUE TITLE
Error when gathering package hashes

### ISSUE THREAD

**Issue by fridex** [thoth-station/solver#299]
```

2019-09-24 16:44:28,681 [1] WARNING  thoth.solver.python.python:345: Requested to install version '0.1' of package 'anyjson', but installed version is '0.1.dev0', error is not fatal
--
  | 2019-09-24 16:44:28,989 [1] CRITICAL root:101: Traceback (most recent call last):
  | File "/opt/app-root/bin/thoth-solver", line 11, in <module>
  | load_entry_point('thoth-solver==1.2.2', 'console_scripts', 'thoth-solver')()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
  | return f(get_current_context(), *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/cli.py", line 139, in pypi
  | subgraph_check_api=subgraph_check_api,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 444, in resolve
  | subgraph_check_api=subgraph_check_api,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 355, in _do_resolve_index
  | entry = _create_entry(package_info, source)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 51, in _create_entry
  | for item in source.get_package_hashes(entry["package_name"], entry["package_version"]):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/source.py", line 372, in get_package_hashes
  | return self._warehouse_get_package_hashes(package_name, package_version, with_included_files)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/source.py", line 132, in _warehouse_get_package_hashes
  | package_info = self._warehouse_get_api_package_version_info(package_name, package_version)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/python/source.py", line 113, in _warehouse_get_api_package_version_info
  | f"Package {package_name} in version {package_version} not found on warehouse {self.url} ({self.name})"
  | thoth.python.exceptions.NotFound: Package anyjson in version 0.1.dev0 not found on warehouse https://pypi.org/simple  (pypi-org)

```

**Comment by fridex** [comment]
This happens on very old releases, it has probably something to do with old PyPI release management.
