### ISSUE TITLE
Solver fails to start in test environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/solver#368]
```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/opt/app-root/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/app-root/bin/thoth-solver", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/opt/app-root/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})
```

**Comment by goern** [comment]
```

2019-11-09 09:44:05,311 [1] INFO     root:123: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-test'
--
  | 2019-11-09 09:44:05,315 [1] INFO     root:160: Logging to rsyslog endpoint is turned off
  | 2019-11-09 09:44:05,752 [1] CRITICAL root:101: Traceback (most recent call last):
  | File "/opt/app-root/bin/thoth-solver", line 8, in <module>
  | sys.exit(cli())
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
  | return f(get_current_context(), *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/cli.py", line 139, in python
  | virtualenv=virtualenv,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 419, in resolve
  | run_command("virtualenv -p " + python_bin + " venv")
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/analyzer/command.py", line 108, in run_command
  | raise CommandError(error_msg, command=command, is_json=is_json)
  | thoth.analyzer.command.CommandError: Command exited with non-zero status code (1): Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 2628, in <module>
  | main()
  | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 870, in main
  | symlink=options.symlink,
  | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 1156, in create_environment
  | install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 1527, in install_python
  | make_exe(py_executable)
  | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 461, in make_exe
  | os.chmod(fn, new_mode)
  | PermissionError: [Errno 1] Operation not permitted: '/home/solver/venv/bin/python3'
  | Sentry is attempting to send 1 pending error messages
  | Waiting up to 2 seconds
  | Press Ctrl-C to quit


```

**Comment by fridex** [comment]
> ```
> 
> 2019-11-09 09:44:05,311 [1] INFO     root:123: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-test'
> --
>   | 2019-11-09 09:44:05,315 [1] INFO     root:160: Logging to rsyslog endpoint is turned off
>   | 2019-11-09 09:44:05,752 [1] CRITICAL root:101: Traceback (most recent call last):
>   | File "/opt/app-root/bin/thoth-solver", line 8, in <module>
>   | sys.exit(cli())
>   | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>   | return self.main(*args, **kwargs)
>   | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
>   | rv = self.invoke(ctx)
>   | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>   | return _process_result(sub_ctx.command.invoke(sub_ctx))
>   | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>   | return ctx.invoke(self.callback, **ctx.params)
>   | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>   | return callback(*args, **kwargs)
>   | File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>   | return f(get_current_context(), *args, **kwargs)
>   | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/cli.py", line 139, in python
>   | virtualenv=virtualenv,
>   | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 419, in resolve
>   | run_command("virtualenv -p " + python_bin + " venv")
>   | File "/opt/app-root/lib/python3.6/site-packages/thoth/analyzer/command.py", line 108, in run_command
>   | raise CommandError(error_msg, command=command, is_json=is_json)
>   | thoth.analyzer.command.CommandError: Command exited with non-zero status code (1): Traceback (most recent call last):
>   | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 2628, in <module>
>   | main()
>   | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 870, in main
>   | symlink=options.symlink,
>   | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 1156, in create_environment
>   | install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
>   | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 1527, in install_python
>   | make_exe(py_executable)
>   | File "/opt/app-root/lib/python3.6/site-packages/virtualenv.py", line 461, in make_exe
>   | os.chmod(fn, new_mode)
>   | PermissionError: [Errno 1] Operation not permitted: '/home/solver/venv/bin/python3'
>   | Sentry is attempting to send 1 pending error messages
>   | Waiting up to 2 seconds
>   | Press Ctrl-C to quit
> ```

Is this still relevant? I was able to run solvers - actually, the ones running on stage were built on test and I haven't spotted this issue after the linked fix.

**Comment by goern** [comment]
well, its a differenct error now:

```

Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
  | ws.require(__requires__)
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
  | needed = self.resolve(parse_requirements(requirements))
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
  | raise VersionConflict(dist, req).with_context(dependent_req)
  | pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/opt/app-root/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})
  | During handling of the above exception, another exception occurred:
  | Traceback (most recent call last):
  | File "/opt/app-root/bin/thoth-solver", line 6, in <module>
  | from pkg_resources import load_entry_point
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
  | @_call_aside
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
  | f(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
  | working_set = WorkingSet._build_master()
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
  | return cls._build_from_requirements(__requires__)
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
  | dists = ws.resolve(reqs, Environment())
  | File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
  | raise VersionConflict(dist, req).with_context(dependent_req)
  | pkg_resources.ContextualVersionConflict: (setuptools 39.2.0 (/opt/app-root/lib/python3.6/site-packages), Requirement.parse('setuptools>=40.3.0'), {'google-auth'})

```

**Comment by fridex** [comment]
I think this can be closed now as its resolved. @goern ack?
