### ISSUE TITLE
Semantic version parsing fails for some package version

### ISSUE THREAD

**Issue by pacospace** [thoth-station/solver#386]
Some versions of some package cannot be parsed.

```
Traceback (most recent call last):
  File "test_queries_.py", line 69, in <module>
    sort_by=QuerySortTypeEnum.PACKAGE_RELEASE
  File "/home/fmurdaca/work/aicoe/storages/TestQueries.py", line 90, in test_get_python_packages_all_versions
    print("\nRESULTS:", cls.graph.get_python_packages_all_versions(**inputs))
  File "/home/fmurdaca/work/aicoe/storages/thoth/storages/graph/postgres.py", line 3234, in get_python_packages_all_versions
    result[package_name] = sorted(versions, key=lambda x: PackageVersion.parse_semantic_version(x[0]), reverse=True)
  File "/home/fmurdaca/work/aicoe/storages/thoth/storages/graph/postgres.py", line 3234, in <lambda>
    result[package_name] = sorted(versions, key=lambda x: PackageVersion.parse_semantic_version(x[0]), reverse=True)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib/python3.6/site-packages/thoth/python/package_version.py", line 183, in parse_semantic_version
    semantic_version = semver.Version.coerce(version_identifier)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib/python3.6/site-packages/semantic_version/base.py", line 238, in coerce
    % version_string
ValueError: Version string lacks a numerical component: '-n.0.18.44-'
```

These packages should be filtered by solver.

**Comment by fridex** [comment]
We no longer use semantic version to parse the string but we rely on the official packaging module I'll close this one, let's see if we observe something similar again in the future.
