### ISSUE TITLE
Issue syncing solvers

### ISSUE THREAD

**Issue by pacospace** [thoth-station/solver#538]
**Describe the bug**
Solvers workflows task for graph-sync is failing.

**To Reproduce**
1. Schedule solver for `textdistance===4.2.0` from PyPI
2. Watch solver workflow created

**Expected behavior**
Solver results are synced successfully in the Thoth database.

**Screenshots**
```
graph-sync-solverany(0):	---> Running application from Python script (app.py) ...
graph-sync-solverany(0):	2020-04-26 05:10:37,398   1 INFO     thoth.common:259: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-stage' and integrations ['SqlalchemyIntegration']
graph-sync-solverany(0):	2020-04-26 05:10:37,402   1 INFO     thoth.common:297: Logging to rsyslog endpoint is turned off
graph-sync-solverany(0):	2020-04-26 05:10:37,403   1 INFO     thoth.graph_sync_job:238: graph-sync-job v0.6.0+thoth_storage.0.22.2+thoth_common.0.10.7 starting...
graph-sync-solverany(0):	2020-04-26 05:10:37,404   1 DEBUG    thoth.graph_sync_job:211: Debug mode is on
graph-sync-solverany(0):	2020-04-26 05:10:37,907   1 INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
graph-sync-solverany(0):	2020-04-26 05:10:37,907   1 INFO     alembic.runtime.migration:161: Will assume transactional DDL.
graph-sync-solverany(0):	2020-04-26 05:10:37,921   1 WARNING  thoth.storages.graph.postgres:258: Database schema is not up to date, you might encounter issues when manipulating with the database
graph-sync-solverany(0):	2020-04-26 05:10:38,703   1 INFO     thoth.storages.graph.postgres:4265: Syncing solver result of package 'textdistance' in version '4.2.0' from 'https://pypi.org/simple' solved by {'os_name': 'fedora', 'os_version': '31', 'python_version': '3.8'}
graph-sync-solverany(0):	2020-04-26 05:10:42,500   1 CRITICAL root:101: Traceback (most recent call last):
graph-sync-solverany(0):	  File "app.py", line 239, in <module>
graph-sync-solverany(0):	    cli()
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
graph-sync-solverany(0):	    return self.main(*args, **kwargs)
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
graph-sync-solverany(0):	    rv = self.invoke(ctx)
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
graph-sync-solverany(0):	    return ctx.invoke(self.callback, **ctx.params)
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
graph-sync-solverany(0):	    return callback(*args, **kwargs)
graph-sync-solverany(0):	  File "app.py", line 219, in cli
graph-sync-solverany(0):	    is_local=local_file,
graph-sync-solverany(0):	  File "app.py", line 119, in _do_sync
graph-sync-solverany(0):	    is_local=is_local,
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 565, in sync_documents
graph-sync-solverany(0):	    to_sync_document_id, force=force, graceful=graceful, graph=graph, is_local=is_local
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 136, in sync_solver_documents
graph-sync-solverany(0):	    graph.sync_solver_result(document)
graph-sync-solverany(0):	  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4353, in sync_solver_result
graph-sync-solverany(0):	    dependency["name"],
graph-sync-solverany(0):	KeyError: 'name'
graph-sync-solverany(0):	Sentry is attempting to send 1 pending error messages
graph-sync-solverany(0):	Waiting up to 2 seconds
graph-sync-solverany(0):	Press Ctrl-C to quit
```

**Additional context**
We recently updated graph-sync-job image on quay because it was two months old.

**Comment by pacospace** [comment]
I'm going to have a look why this is happening with the new image.

**Comment by pacospace** [comment]
Re opened in thoth-storages where it actually belongs.
