### ISSUE TITLE
solver-fedora-32-py37 fails

### ISSUE THREAD

**Issue by fridex** [thoth-station/solver#607]
**Describe the bug**

Fedora based Python 3.7 solvers fail with the following exception:

```
solver-fedora-32-py37-f6c70825-3353680581: During handling of the above exception, another exception occurred:
solver-fedora-32-py37-f6c70825-3353680581: ModuleNotFoundError: No module named 'importlib.metadata'
solver-fedora-32-py37-f6c70825-3353680581: ModuleNotFoundError: No module named 'importlib_metadata'
solver-fedora-32-py37-f6c70825-3353680581:   File "<string>", line 38, in <module>
solver-fedora-32-py37-f6c70825-3353680581: 
solver-fedora-32-py37-f6c70825-3353680581:   File "<string>", line 5, in _get_importlib_metadata_metadata
solver-fedora-32-py37-f6c70825-3353680581: 2020-09-09 10:49:24,518   1 DEBUG    thoth.solver.python.instrument:190: stderr during command execution: Traceback (most recent call last):
solver-fedora-32-py37-f6c70825-3353680581:   File "<string>", line 7, in _get_importlib_metadata_metadata
solver-fedora-32-py37-f6c70825-3353680581: 2020-09-09 10:49:24,518   1 DEBUG    thoth.solver.python.python:86: Removing installed package 'selinon'
solver-fedora-32-py37-f6c70825-3353680581: 2020-09-09 10:49:25,236   1 DEBUG    thoth.solver.python.python:99: Restoring previous environment setup after installation of 'selinon' (None)
solver-fedora-32-py37-f6c70825-3353680581: Traceback (most recent call last):
solver-fedora-32-py37-f6c70825-3353680581: ModuleNotFoundError: No module named 'importlib.metadata'
solver-fedora-32-py37-f6c70825-3353680581: 
```

**To Reproduce**
1. Run thoth-solver which is installed in solver-fedora-32-py37 environment
2. See error

**Expected behavior**

The solver should successfully analyze packages.

**Comment by fridex** [comment]
The issue is caused by this line:

https://github.com/thoth-station/solver/blob/799266429f1adaead649964ea9cbc74ea2d1eddb/dockerfile/Dockerfile.solver-fedora-32-py37#L17

Fedora 32 is shipped with Python 3.8 by default. The pip that is run is run using Python 3.8 and installs thoth-solver into the environment. This causes that importlib-metadata is not installed given the environment marker:

https://github.com/thoth-station/solver/blob/799266429f1adaead649964ea9cbc74ea2d1eddb/requirements.txt#L4

Subsequently, Python 3.7 environment is created:

https://github.com/thoth-station/solver/blob/799266429f1adaead649964ea9cbc74ea2d1eddb/dockerfile/Dockerfile.solver-fedora-32-py37#L22

As Python 3.7 virtual env is used when running solver, it failes importing `importlib-metadata` backport as well as `importlib.metadata` from the standard library as importlib is available only starting Python version 3.8.
