### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by harshad16** [thoth-station/solver#684]
**Describe the bug**
solver with v1.7.1 is failing due to the value error. 

```
Traceback (most recent call last):
  File "thoth/solver/cli.py", line 154, in <module>
    cli()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 229, "funcname": "_send_event", "created": 1614917577.5606315, "asctime": "2021-03-05 04:12:57,560", "msecs": 560.631513595581, "relative_created": 1450.2780437469482, "process": 22, "message": "Sending event, type:null level:error event_id:5bfa3b1853ab427eb62570da6ea31446 project:1298083 host:sentry.io"}
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "thoth/solver/cli.py", line 140, in python
    virtualenv=virtualenv,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 357, in resolve
    environment_packages = get_environment_packages(python_bin)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/python.py", line 57, in get_environment_packages
    package_name, package_version = line.split("==", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by harshad16** [comment]
Caused by the package: `'thoth-solver @ file:///opt/app-root/src`

**Comment by harshad16** [comment]
```
(app-root) /opt/app-root/src/solver-venv/bin/python3 -m pip show thoth-solver
Name: thoth-solver
Version: 1.7.1
Summary: Tool and library for discovering package dependencies in PyPI world
Home-page: https://github.com/thoth-station/solver
Author: Fridolin Pokorny
Author-email: fridolin@redhat.com
License: GPLv3+
Location: /opt/app-root/lib/python3.6/site-packages
Requires: autopep8, requests, thoth-analyzer, thoth-python, virtualenv, importlib-metadata, click, pipdeptree, packaging, attr, thoth-common
Required-by:
```

**Comment by fridex** [comment]
If I understand correctly, this is caused by solver not able to detect itself as it is run in s2i. Will open a PR for this. Thanks for the report! :+1:
